config/routes.rb
PetroleumAccounting::Application.routes.draw do
	namespace :catalogs do
		resources :employees
		resources :customers do 
			get 'new_contract', on: :collection
			get 'get_contracts', on: :collection
		end
		resources :organizations do 
			get 'new_department', on: :collection
			get 'get_departments', on: :collection 
		end
		resources :products
		resources :promotions
	end
	resources :prices

	namespace :documents do 
		resources :talons_issues do 
			get 'new_issue', on: :collection, to: 'actions/talons/issues#new'
		end
		resources :talons_repaids do 
			get 'new_repaid', on: :collection, to: 'actions/talons/repaids#new'
		end
	end
	root 'sessions#new'
	get 'employee_profile', to: 'profiles/employee#show'
	get 'customer_profile', to: 'profiles/customer#show'
	resources :sessions
	match '/signup' => 'sessions#signup', via: [:get, :post]
	match '/reset_password' => 'sessions#reset_password', via: [:get, :post]
	match '/signin' => 'sessions#new', via: :get
	match '/signout' => 'sessions#destroy', via: :delete

	

end

app/views/navigation/right_panel/_panel.html.slim
#flash_notice.pull-left.hide
	== render '/flash_notice' 
.user.pull-right
	= link_to(content_tag(:i,"",class: "icon-user icon-2x") +  " " + current_user.view + " | Выход", signout_path, method: :delete)
.navs.dropdown
	ul.dropdown-menu style="display: block;"
		== render "navigation/top_panel/catalogs"
		== render "navigation/top_panel/documents"
		li = link_to(content_tag(:i,"",class: "icon-th-list") + " Реклама",  catalogs_promotions_path)
		li.divider
		li = link_to(content_tag(:i,"",class: "icon-th-list") + " Цены",  prices_path)