config/routes.rb
PetroleumAccounting::Application.routes.draw do
	namespace :catalogs do
		resources :employees
		resources :customers do 
			get 'new_contract', on: :collection
			get 'get_contracts', on: :collection
		end
		resources :organizations do 
			get 'new_department', on: :collection
			get 'get_departments', on: :collection 
		end
		resources :products
		resources :promotions
	end
	resources :prices

	namespace :documents do 
		resources :talons_issues do 
			get 'new_issue', on: :collection, to: 'actions/talons/issues#new'
		end
		resources :talons_repaids do 
			get 'new_repaid', on: :collection, to: 'actions/talons/repaids#new'
		end
	end
	root 'sessions#new'
	get 'employee_profile', to: 'profiles/employee#show'
	get 'customer_profile', to: 'profiles/customer#show'
	resources :sessions
	match '/signup' => 'sessions#signup', via: [:get, :post]
	match '/reset_password' => 'sessions#reset_password', via: [:get, :post]
	match '/signin' => 'sessions#new', via: :get
	match '/signout' => 'sessions#destroy', via: :delete

	

end

app/views/navigation/top_panel/_catalogs.html.slim
li.dropdown-submenu.pull-left
	a tabindex="-1" href="#" 
		|Справочники
	ul.dropdown-menu
		li = link_to(content_tag(:i,"",class: "icon-th-list") + " Клиенты", catalogs_customers_path)
		li = link_to(content_tag(:i,"",class: "icon-th-list") + " Организации", catalogs_organizations_path)
		li = link_to(content_tag(:i,"",class: "icon-th-list") + " Нефтепродукты", catalogs_products_path)
		li = link_to(content_tag(:i,"",class: "icon-th-list") + " Пользователи", catalogs_employees_path)

app/views/navigation/top_panel/_control_panel.html.slim
.navbar
	.navbar-inner
		.container
			a.brand = yield :title
			ul.nav.pull-right
				li.divider-vertical
				- if defined? buttons
					- buttons.each do |btn|
						= content_tag :a, content_tag(:i, " #{btn[:title]}", class: "icon-plus"), class: 'btn', data: {path: btn[:request_path], target: "#new-media"}

app/views/navigation/top_panel/_documents.html.slim
li.dropdown-submenu.pull-left
	a tabindex="-1" href="#" 
		|Документы
	ul.dropdown-menu
		li = link_to(content_tag(:i,"",class: "icon-th-list") + " Реализация талонов", documents_talons_issues_path)
		li = link_to(content_tag(:i,"",class: "icon-th-list") + " Погашение талонов", documents_talons_repaids_path)

app/views/navigation/top_panel/_panel.html.slim
#control-panel
	= yield :control_panel
.container
	#new-media.media-window.hide
#right-panel
	== render 'navigation/right_panel/panel'